[project]
name = "py-taxi-service-startproject"
version = "0.1.0"
description = "Django Taxi Service Project"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.6",
    "pre-commit>=4.1.0",
    "pytest==8.3.5",
    "pytest-django==4.10.0",
    "ruff==0.9.9",
]

[tool.ruff]
# excludes
exclude = ["tests", "migrations", ".venv"]
# Длина строки
line-length = 79

[tool.ruff.lint]
# E — pycodestyle (Style errors, ошибки стиля, например, пробелы, отступы)
# F — pyflakes (Ошибки, например, неиспользуемые переменные, импорт)
# W — pycodestyle (Предупреждения о стиле)
# N — PEP8 Naming (Неправильные имена переменных, классов, функций)
# ANN — flake8-annotations (Проблемы с аннотациями типов)
# UP — pyupgrade (Советы по обновлению кода, например, использование новых фич Python)
# I — isort (Проблемы с сортировкой импортов)
# Q — Лапки (flake8-quotes) – перевірка на подвійні/одинарні лапки.
# PL — Стилістичні помилки (Pylint) – дублювання, порушення PEP8.
# SIM —	Спрощення (flake8-simplify) – зайві if, непотрібний код.
# ARG — Перевірка аргументів функцій (flake8-unused-arguments).

ignore = ["N999", "PLR0913", "ANN002", "ANN003"]
select = ["E", "F", "W", "N", "ANN", "UP", "I", "Q", "PL", "SIM", "ARG"]

[tool.ruff.format]
exclude = ["tests", "migrations", ".venv"]
quote-style = "double"  # Наприклад, змінити лапки на подвійні (необов'язково)